package config

import (
	"fmt"
	"sort"
	"strings"
)

// FormatDocumentedConfigFile serializes a GameConfigFile into a clean, human-readable,
// fully documented TOML format with helpful comments for users.
func FormatDocumentedConfigFile(fileCfg *GameConfigFile) string {
	if fileCfg == nil {
		return ""
	}

	var b strings.Builder
	b.WriteString("# ==============================================================================\n")
	b.WriteString("# rpt Configuration Specification (rpt.toml)\n")
	b.WriteString("# Generated by run-proton-tui with Clean Zero Baseline standards\n")
	b.WriteString("# ==============================================================================\n\n")

	activeProfile := fileCfg.ActiveProfile
	if activeProfile == "" {
		activeProfile = "default"
	}
	b.WriteString("# Currently active profile name\n")
	b.WriteString(fmt.Sprintf("active_profile = %q\n\n", activeProfile))

	// Collect profile names in order, putting active profile first
	var names []string
	for name := range fileCfg.Profiles {
		if name != activeProfile {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	orderedProfiles := append([]string{activeProfile}, names...)

	for _, name := range orderedProfiles {
		prof, ok := fileCfg.Profiles[name]
		if !ok || prof == nil {
			continue
		}
		formatProfile(&b, name, prof)
	}

	return b.String()
}

func formatProfile(b *strings.Builder, name string, cfg *GameConfig) {
	b.WriteString("# ------------------------------------------------------------------------------\n")
	b.WriteString(fmt.Sprintf("# Profile: %q (Self-Contained Configuration)\n", name))
	b.WriteString("# ------------------------------------------------------------------------------\n")
	b.WriteString(fmt.Sprintf("[profiles.%s]\n\n", name))

	// 1. Core Execution Settings
	b.WriteString("# --- 1. Core Execution Settings ---\n")
	b.WriteString(fmt.Sprintf("target_exe = %q # Target Windows binary (relative to game dir)\n", cfg.TargetExe))
	b.WriteString(fmt.Sprintf("proton_path = %q # Absolute path to Proton runner executable\n", cfg.ProtonPath))
	b.WriteString(fmt.Sprintf("app_id = %q # Steam AppID for UMU fixes and ProtonDB queries\n", cfg.AppID))
	b.WriteString(fmt.Sprintf("extra_args = %s # Extra CLI flags passed directly to game executable\n", formatStringSlice(cfg.ExtraArgs)))
	if cfg.PresetName != "" {
		b.WriteString(fmt.Sprintf("preset_name = %q # Active quirks preset name\n", cfg.PresetName))
	}
	if cfg.UmuID != "" {
		b.WriteString(fmt.Sprintf("umu_id = %q # UMU game database identifier\n", cfg.UmuID))
	}
	b.WriteString("\n")

	// 2. Hardware, Sandbox & Performance Controls
	b.WriteString("# --- 2. Hardware, Sandbox & Performance Controls ---\n")
	b.WriteString(fmt.Sprintf("use_gamescope = %t # Run inside Gamescope nested micro-compositor\n", cfg.UseGamescope))
	b.WriteString(fmt.Sprintf("gamescope_output = %q # Target DRM display (\"auto\" lets host compositor decide)\n", cfg.GamescopeOutput))

	if cfg.GeometryAutoDetected {
		b.WriteString("# auto detected from TUI\n")
	}
	b.WriteString(fmt.Sprintf("gamescope_width = %d # Resolution canvas width (0 = auto/native display)\n", cfg.GamescopeWidth))
	b.WriteString(fmt.Sprintf("gamescope_height = %d # Resolution canvas height (0 = auto/native display)\n", cfg.GamescopeHeight))
	b.WriteString(fmt.Sprintf("gamescope_refresh = %d # Refresh rate in Hz (0 = native/untouched)\n", cfg.GamescopeRefresh))

	if cfg.GamescopeScaling != "" {
		b.WriteString(fmt.Sprintf("gamescope_scaling = %q # Upscaler type (fit, fill, stretch, integer, auto)\n", cfg.GamescopeScaling))
	}
	if cfg.GamescopeFilter != "" {
		b.WriteString(fmt.Sprintf("gamescope_filter = %q # Upscaler filter (linear, fsr, nis, nearest, auto)\n", cfg.GamescopeFilter))
	}
	if cfg.GamescopeSharpness > 0 {
		b.WriteString(fmt.Sprintf("gamescope_sharpness = %d # FSR/NIS sharpness level (0-20)\n", cfg.GamescopeSharpness))
	}
	b.WriteString(fmt.Sprintf("gamescope_window_mode = %q # Window mode (fullscreen, borderless, windowed)\n", cfg.GamescopeWindowMode))
	if cfg.GamescopeAdaptiveSync {
		b.WriteString(fmt.Sprintf("gamescope_adaptive_sync = %t # Enable variable refresh rate (VRR)\n", cfg.GamescopeAdaptiveSync))
	}
	if cfg.GamescopeMangoApp {
		b.WriteString(fmt.Sprintf("gamescope_mangoapp = %t # Enable MangoHud micro-overlay inside Gamescope\n", cfg.GamescopeMangoApp))
	}
	if cfg.GamescopeHDR {
		b.WriteString(fmt.Sprintf("gamescope_hdr = %t # Enable High Dynamic Range (HDR) passthrough\n", cfg.GamescopeHDR))
	}
	if cfg.GamescopeFPSLimit > 0 {
		b.WriteString(fmt.Sprintf("gamescope_fps_limit = %d # Framerate limit (0 = uncapped)\n", cfg.GamescopeFPSLimit))
	}
	if len(cfg.GamescopeExtraArgs) > 0 {
		b.WriteString(fmt.Sprintf("gamescope_extra_args = %s # Extra CLI flags passed directly to Gamescope\n", formatStringSlice(cfg.GamescopeExtraArgs)))
	}

	b.WriteString(fmt.Sprintf("use_prime_run = %t # Offload 3D rendering to NVIDIA dGPU via prime-run\n", cfg.UsePrimeRun))
	b.WriteString(fmt.Sprintf("use_pcores = %t # Pin execution to Intel Performance cores (taskset)\n", cfg.UsePCores))
	b.WriteString(fmt.Sprintf("pcores_mask = %q # Thread affinity mask for Performance cores\n", cfg.PCoresMask))
	b.WriteString(fmt.Sprintf("manage_power = %t # Automatically request system performance power profile\n", cfg.ManagePower))
	b.WriteString(fmt.Sprintf("use_xalia = %t # Enable Proton Xalia UI accessibility bridge\n", cfg.UseXalia))
	b.WriteString(fmt.Sprintf("enable_logging = %t # Capture verbose Proton, DXVK, and VKD3D logs (.logs/)\n", cfg.EnableLogging))
	if cfg.EnableLocalTelemetry {
		b.WriteString(fmt.Sprintf("enable_local_telemetry = %t # Record anonymous local session metrics\n", cfg.EnableLocalTelemetry))
	}
	b.WriteString(fmt.Sprintf("opaque_backdrop = %t # TUI visual styling: opaque or transparent\n", cfg.OpaqueBackdrop))
	b.WriteString("\n")

	// 3. Process Supervision & Hooks
	b.WriteString("# --- 3. Process Supervision & Diagnostics ---\n")
	b.WriteString(fmt.Sprintf("wait_processes = %s # Background updater/child processes to supervise\n", formatStringSlice(cfg.WaitProcesses)))
	if cfg.DisplayFile != "" {
		b.WriteString(fmt.Sprintf("display_file = %q # File to write current $DISPLAY socket to\n", cfg.DisplayFile))
	}
	if cfg.BackupDir != "" {
		b.WriteString(fmt.Sprintf("backup_dir = %q # Preservation destination for prefix resets\n", cfg.BackupDir))
	}
	if cfg.PreLaunchHook != "" {
		b.WriteString(fmt.Sprintf("pre_launch_hook = %q # Custom script executed before launch\n", cfg.PreLaunchHook))
	}
	if cfg.PostExitHook != "" {
		b.WriteString(fmt.Sprintf("post_exit_hook = %q # Custom script executed after game exit\n", cfg.PostExitHook))
	}
	b.WriteString("\n")

	// 4. Custom Environment Variables
	if len(cfg.EnvVars) > 0 {
		b.WriteString(fmt.Sprintf("# --- 4. Custom Environment Variables ---\n[profiles.%s.env_vars]\n", name))
		var envKeys []string
		for k := range cfg.EnvVars {
			envKeys = append(envKeys, k)
		}
		sort.Strings(envKeys)
		for _, k := range envKeys {
			comment := getEnvComment(k)
			if comment != "" {
				b.WriteString(fmt.Sprintf("%s = %q # %s\n", k, cfg.EnvVars[k], comment))
			} else {
				b.WriteString(fmt.Sprintf("%s = %q\n", k, cfg.EnvVars[k]))
			}
		}
		b.WriteString("\n")
	}

	// 5. DLL Overrides
	if len(cfg.DLLOverrides) > 0 {
		b.WriteString(fmt.Sprintf("# --- 5. DLL Overrides (WINEDLLOVERRIDES) ---\n[profiles.%s.dll_overrides]\n", name))
		var dllKeys []string
		for k := range cfg.DLLOverrides {
			dllKeys = append(dllKeys, k)
		}
		sort.Strings(dllKeys)
		for _, k := range dllKeys {
			b.WriteString(fmt.Sprintf("%q = %q\n", k, cfg.DLLOverrides[k]))
		}
		b.WriteString("\n")
	}

	// 6. Filesystem Directives
	if len(cfg.Filesystem.EnsureDirs) > 0 || len(cfg.Filesystem.Symlinks) > 0 || len(cfg.Filesystem.ExtraBackupPaths) > 0 {
		b.WriteString(fmt.Sprintf("# --- 6. Declarative Filesystem Directives ---\n[profiles.%s.filesystem]\n", name))
		if len(cfg.Filesystem.EnsureDirs) > 0 {
			b.WriteString(fmt.Sprintf("ensure_dirs = %s\n", formatStringSlice(cfg.Filesystem.EnsureDirs)))
		}
		if len(cfg.Filesystem.ExtraBackupPaths) > 0 {
			b.WriteString(fmt.Sprintf("extra_backup_paths = %s\n", formatStringSlice(cfg.Filesystem.ExtraBackupPaths)))
		}
		for _, sym := range cfg.Filesystem.Symlinks {
			b.WriteString(fmt.Sprintf("\n[[profiles.%s.filesystem.symlinks]]\nsource = %q\ntarget = %q\n", name, sym.Source, sym.Target))
		}
		b.WriteString("\n")
	}

	// 7. Cloud Sync Directives
	if cfg.CloudSync != nil && (cfg.CloudSync.Backend != "" || cfg.CloudSync.RemotePath != "") {
		b.WriteString(fmt.Sprintf("# --- 7. Cloud Save Sync Configuration ---\n[profiles.%s.cloud_sync]\n", name))
		b.WriteString(fmt.Sprintf("backend = %q\n", cfg.CloudSync.Backend))
		b.WriteString(fmt.Sprintf("remote_path = %q\n", cfg.CloudSync.RemotePath))
		b.WriteString(fmt.Sprintf("local_path = %q\n", cfg.CloudSync.LocalPath))
		b.WriteString(fmt.Sprintf("auto_sync_pre = %t\n", cfg.CloudSync.AutoSyncPre))
		b.WriteString(fmt.Sprintf("auto_sync_post = %t\n\n", cfg.CloudSync.AutoSyncPost))
	}

	// 8. Per-Executable Profiles
	if len(cfg.Profiles) > 0 {
		var exeKeys []string
		for k := range cfg.Profiles {
			exeKeys = append(exeKeys, k)
		}
		sort.Strings(exeKeys)
		for _, exe := range exeKeys {
			ep := cfg.Profiles[exe]
			if ep != nil {
				formatExeProfile(b, name, exe, ep)
			}
		}
	}
}

func formatExeProfile(b *strings.Builder, profName, exeName string, ep *ExecutableProfile) {
	b.WriteString(fmt.Sprintf("# Per-Executable Profile: %s\n", exeName))
	b.WriteString(fmt.Sprintf("[profiles.%s.profiles.%q]\n", profName, exeName))
	b.WriteString(fmt.Sprintf("target_exe = %q\n", ep.TargetExe))
	if ep.UseGamescope != nil {
		b.WriteString(fmt.Sprintf("use_gamescope = %t\n", *ep.UseGamescope))
	}
	if ep.GamescopeOutput != "" {
		b.WriteString(fmt.Sprintf("gamescope_output = %q\n", ep.GamescopeOutput))
	}
	if ep.GamescopeWidth > 0 {
		b.WriteString(fmt.Sprintf("gamescope_width = %d\n", ep.GamescopeWidth))
	}
	if ep.GamescopeHeight > 0 {
		b.WriteString(fmt.Sprintf("gamescope_height = %d\n", ep.GamescopeHeight))
	}
	if ep.GamescopeRefresh > 0 {
		b.WriteString(fmt.Sprintf("gamescope_refresh = %d\n", ep.GamescopeRefresh))
	}
	if ep.UsePrimeRun != nil {
		b.WriteString(fmt.Sprintf("use_prime_run = %t\n", *ep.UsePrimeRun))
	}
	if ep.UsePCores != nil {
		b.WriteString(fmt.Sprintf("use_pcores = %t\n", *ep.UsePCores))
	}
	if ep.PCoresMask != "" {
		b.WriteString(fmt.Sprintf("pcores_mask = %q\n", ep.PCoresMask))
	}
	if ep.ManagePower != nil {
		b.WriteString(fmt.Sprintf("manage_power = %t\n", *ep.ManagePower))
	}
	if len(ep.ExtraArgs) > 0 {
		b.WriteString(fmt.Sprintf("extra_args = %s\n", formatStringSlice(ep.ExtraArgs)))
	}
	if len(ep.WaitProcesses) > 0 {
		b.WriteString(fmt.Sprintf("wait_processes = %s\n", formatStringSlice(ep.WaitProcesses)))
	}
	if len(ep.EnvVars) > 0 {
		b.WriteString(fmt.Sprintf("\n[profiles.%s.profiles.%q.env_vars]\n", profName, exeName))
		var keys []string
		for k := range ep.EnvVars {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("%s = %q\n", k, ep.EnvVars[k]))
		}
	}
	b.WriteString("\n")
}

func formatStringSlice(slice []string) string {
	if len(slice) == 0 {
		return "[]"
	}
	var quoted []string
	for _, s := range slice {
		quoted = append(quoted, fmt.Sprintf("%q", s))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func getEnvComment(key string) string {
	switch key {
	case "WINE_CANONICAL_HOLE":
		return "Prevents anti-cheat page fault crashes"
	case "VKD3D_CONFIG":
		return "D3D12 memory staging configuration (e.g. no_upload_hvv prevents 8GB VRAM thrashing)"
	case "PROTON_USE_XALIA":
		return "Proton accessibility bridge (0=disabled to prevent CEF crashes)"
	case "UMU_ID":
		return "Upstream UMU gamefixes database identifier"
	case "PROTON_ENABLE_NVAPI":
		return "Enables NVIDIA NVAPI features in Proton"
	case "DXVK_ENABLE_NVAPI":
		return "Enables NVIDIA NVAPI features in DXVK"
	case "STEAMOS", "STEAMDECK":
		return "Exposes SteamOS / Steam Deck environment shims"
	default:
		return ""
	}
}
